name: Check Markdown links

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  schedule:
    # Every Monday at 1p UTC https://crontab.guru/#0_13_*_*_1
    - cron: "0 13 * * 1"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: "mlc_config.json"

          # Quiet mode only shows errors in output not successful links too
          use-quiet-mode: "yes"

          # Specify yes to show detailed HTTP status for checked links.
          use-verbose-mode: "yes"
