name: Python CI Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"

    - name: Run Lighthouse CI
      uses: treosh/lighthouse-ci-action@v2
      with:
        configPath: "./lighthouserc.json"
        temporaryPublicStorage: true
