name: Linting Docs

on:
  pull_request:
  check_run:
    types: [created, completed]

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Vale
      uses: errata-ai/vale-action@reviewdog
      with:
          reporter: github-pr-check
          fail_on_error: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
